### ISSUE TITLE
Websites 'Christmas list'

### ISSUE THREAD

**Issue by Huaraz2** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#25]
Right here goes nothing, there are several things that I think we should do to make the website more useful to everyone else, don't hate me :smile:.

1. languages - the only page with stuff in it in the one on C.
 - [x] - C++ needs to be done as when people think of programming languages they often think of this one first. @chelyabinsk fancy doing this one?
 - [x] - Brainf**k @Aurora256 could you do this one? (she has done this I believe but someone needs to show her how to put it on the site)
 - [x] - Haskell @alcarney as this was your favourite langauage last year. 
 - [x] - Java @sluenenglish or @geraintpalmer maybe? there is the third year(was on placement last year) who sits in code club where we used to last year in code club who you could ask for help.
 - [ ] - Python @StephanieAngharad you said you would do this 
 - [ ] - VB/VBA @timothyf1 could you do this one as you did it at A-level and last year in the spring.

  <b>On each page we need a brief description about the language and then two pieces of code, one of a function that prints out `Hello World`, one function that outputs the number of lines in a file and one random/fancy one</b>

2. Editors - The best 2 are already there: Atom and Vim.
 - [ ] - Sublime @geraintpalmer and @hhlorrimore as you use it? @geraintpalmer i don't want to see your credit card details here though :credit_card: :stuck_out_tongue_winking_eye: 
 - [x] - Emacs @alcarney could you write something about this 'OS'
 - [x] - notepad I will do this one, I have a plan.
 - [x] - idle @Enyexlaw as you were the first Padawan could you do this one.

3. The Menu bar
- [x] - It is getting a bit crowded now and I think that we need to have a discussion on how to best set it up. Me and @timothyf1 will then go about making it happen.

4. How To - With me and @timothyf1 leaving at the end of the year, this would be helpful for the future members
 - [x] - draft blog post with examples of how to do things in it I will do this.
 - [ ] - How to become a contributor to the website and how your title is made. This replaces #19 
 - [x] - what the past sessions page is about and editing it. I will do this aas I am the one who edits it at the moment.

5. New Gource video
 - [x] - the one on the website currently only does the first ten weeks of the website. I think one big one is too long so I think we should split iit into one for each term. Me and @alcarney could look at this.

Good luck Guys. :smiling_imp: :shipit: :metal: :credit_card: :chicken: :ambulance:

**Comment by Huaraz2** [comment]
:disappointed: you can't assign more than one person to an issue

**Comment by drvinceknight** [comment]
Great issue @Huaraz2! Let's all chat here and say when we'll work on stuff :+1:

**Comment by alcarney** [comment]
Also is it about time for an updated Gourd video? Maybe at the end of the semester we make a new one?

**Comment by drvinceknight** [comment]
Yeah good idea!

**Comment by chelyabinsk** [comment]
Yes, I'll do that

**Comment by Huaraz2** [comment]
cool

**Comment by Huaraz2** [comment]
I have done the draft blog post with 4c2ea507c3dc1f425218b2014e618817b4701b28

**Comment by alcarney** [comment]
Testing 

[  ] Not done 
[X] Done

**Comment by alcarney** [comment]
Would it be good to come up with a list of standard programs that we share code for on each language page, so that it makes it easy for people to compare how the various different languages work?

Then on top of that add more complex programs that demonstrate the "notable features" of each language?

**Comment by Huaraz2** [comment]
Sounds like a good idea, what did you have in mind @alcarney?

**Comment by drvinceknight** [comment]
Something like Fibonacci? Or perhaps (because that's more or less
everywhere) a random walk?

**Comment by alcarney** [comment]
Well how does three programs sound?

One trivial one (Hello world)
One that's not exactly trivial but simple enough to wet your whistle
(Counting the number of lines in a file)

Now the last one I feel should be complicated enough so that you use most
of the standard features of the language but simple enough so that:

- The language's standard library is sufficient
- Fits in a file of reasonable length so we don't have to worry about build
systems.

I'm not too sure what sort of thing would satisfy all that so any ideas
would be good :)

It might also be a good idea to include a "Getting Started" track of
tutorials for each language - just as we are planning to do for the website.

Oh! How does this sound? Each of the three "standard programs" form the
getting started track of tutorials. We still include the code on the
language page but each tutorial will show you how to arrive at those
programs. So the first could be installing whatever you need to run the
language and getting to Hello World. The second introduces basic language
syntax etc.

Then each of the "notable feature" programs are also accompanied with a
tutorial explaining said notable feature?

**Comment by drvinceknight** [comment]
This sounds like a great idea. We could have the installation guides for
different OSs as well.

Vince

**Comment by alcarney** [comment]
@Huaraz2 how would you feel is we close this now and open separate issues for the remaining items? It might fit in better with the new project system and it could be easier for people to come along and start picking items to work on
